-- 1.数据类型
BIGINT
-- 只能是整数，不能有小数
NUMERIC
-- NUMERIC 只能是数字，不能有小数  
-- NUMERIC(4,2) 表示总共有4位数字，其中2位是小数 12.12
TEXT
-- 字符串类型
VARCHAR(4)
-- 字符串类型，最多4个字符 "1234"
BOOLEAN
-- 布尔类型，只能是 true 或 false
TIMESTAMPTZ
-- 时间类型，带时区
JSONB
-- JSON 类型
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
-- id 自动生成，不用手填，手填会报错（严格自增，不允许人为干预（推荐用于纯自增主键））
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
-- id 自动生成，不用手填，手填不会报错（需要兼容数据迁移、批量导入等场景）
name VARCHAR(50) NOT NULL -- 字符串类型，最多50个字符，不能为空
price NUMERIC(10, 2) NOT NULL -- 数字类型，最多10位，其中2位小数，不能为空
created_at TIMESTAMPTZ NOT NULL DEFAULT now () BIGINT NUMERIC(10, 2) TEXT VARCHAR(4) BOOLEAN TIMESTAMPTZ JSONB PRIMARY KEY UNIQUE NOT NULL completed BOOLEAN NOT NULL DEFAULT FALSE
-- 2.约束 
PRIMARY KEY -- 主键约束，唯一，非空
NOT NULL -- 约束，非空
UNIQUE -- 唯一约束，唯一
DEFAULT -- 默认值约束，默认值
FOREIGN KEY -- 外键约束，引用其他表的主键
CHECK -- 检查约束，检查值是否符合要求
CREATE TABLE
  users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id2 BIGINT NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL,
    password_hash text NOT NULL
  );

CREATE TABLE
  tasks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE -- ← 单独声明
  );

CREATE TABLE
  tasks1 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- 自增主键
    user_id BIGINT NOT NULL REFERENCES users (id), --和 RESTRICT 相同
    title TEXT NOT NULL,
    user_id2 BIGINT NOT NULL REFERENCES users (id),
    user_id3 BIGINT REFERENCES users (id) ON DELETE SET NULL,
    user_id4 BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    -- user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    -- FOREIGN KEY (user_id, user_id2, ) REFERENCES users(id, id2,)
  );

CREATE TABLE
  tasks2 (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL,
    user_id2 BIGINT NOT NULL,
    FOREIGN KEY (user_id,) REFERENCES users (id,) ON DELETE CASCADE,
  )
CREATE TABLE
  tasks3 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_id2 BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_id3 BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  );

-- CHECK练习
CREATE TABLE
  tasks4 (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    title TEXT CHECK (length (title) > 0), -- 标题长度大于0
    title1 TEXT CHECK (length (title1) BETWEEN 1 AND 200), -- 标题长度 1~200
    title2 TEXT NOT NULL CHECK (char_length(title2) BETWEEN 1 AND 200), -- 标题长度 1~200
    status TEXT CHECK (status in ('a', 'b', 'c')) -- 状态必须是 a, b, c 中的一个
    discount BIGINT CHECK (
      discount >= 0
      AND discount <= 100
    ),
    title3 TEXT NOT NULL,
    email TEXT NOT NULL,
    CHECK (email LIKE '%_@_%._%'),
    CHECK (trim(email) <> ''), --<> 相当于 !=
    CHECK (
      length (title) BETWEEN 1 AND 200
      OR title1 NOT NULL
    ),
  )
CREATE TABLE
  tasks5 (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, -- 自增主键
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE, -- 用户ID，外键，引用users表的id列，级联删除
    status TEXT CHECK (status IN ('a', 'b', 'c')), -- 状态必须是 a, b, c 中的一个
    flag BOOLEAN NOT NULL DEFAULT FALSE,
    -- FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  )